apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ibm-qaoa-workspace
  namespace: usra-expedetions
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: rook-cephfs
